[rrc2022]
task = "push"  # "push" or "lift"
dataset_type = "expert"  # "expert or "mixed"

push_mixed_policy = "rrc2022.evaluate_push_mix.PushMixedPolicy"
push_expert_policy = "rrc2022.evaluate_push_exp.PushExpertPolicy"
lift_mixed_policy = "rrc2022.evaluate_lift_mix_norm.LiftMixedPolicy"
lift_expert_policy = "rrc2022.evaluate_lift_exp_norm.LiftExpertPolicy"

#lift_mixed_policy = "rrc2022.evaluate_lift_mix.LiftMixedPolicy"
#lift_expert_policy = "rrc2022.evaluate_lift_exp.LiftExpertPolicy"
#push_mixed_policy = "rrc2022.evaluate_push_mix_norm.PushMixedPolicy"
#push_expert_policy = "rrc2022.evaluate_push_exp_norm.PushExpertPolicy"
